<?php if ($cl['li']['advertising']): ?>
	<?php echo cl_template('timeline/ad'); ?>
<?php else: ?>

    <?php if (isset($_GET['cat_id'])): ?>
    
     <?php if (($_GET['cat_id']) == $cl['li']['cat_id']): ?>
        <?php echo cl_template('timeline/post_inner'); ?>
     <?php endif; ?>
        
    <?php else: ?>
        <?php echo cl_template('timeline/post_inner'); ?>
    <?php endif; ?>
        
    
<?php endif; ?>