<div class="cp-app-container" data-app="about_settings">
   <div class="container-fluid">
      <div class="page-title">
         <div class="row">
            <div class="col-6">
               <h3>Posts Page </h3>
            </div>
            <div class="col-6">
               <ol class="breadcrumb">
                  <li class="breadcrumb-item"> <a href="<?php echo cl_link('admin_panel'); ?>">                                    <i data-feather="home"></i></a></li>
                  <li class="breadcrumb-item">    <?php echo cl_translate('Categories'); ?></li>
               </ol>
            </div>
         </div>
      </div>
   </div>
   <div class="container-fluid vueCat">
      <div class="row">
         <div class="col-sm-12">
            <div class="card"  style="padding: 15px;">
               <div class="card-header">
                  <h5>
                     Posts
                  </h5>
               </div>
               <div class="row mb-3 mt-4">
                   <div class="col-md-3">
                        <label for="username">Username:</label>
                        <input type="text" class="form-control" placeholder="Enter username to search" id="username" v-model='search.username'>
                   </div>
                   
                   <div class="col-md-3">
                        <label for="text">Text:</label>
                        <input type="text" class="form-control" placeholder="Enter text to search" id="text"  v-model='search.text'>
                   </div>
                   
                   <div class="col-md-3 pt-4">
                      <button type="button" class="btn btn-primary" v-on:click="searchPost()">Search <i class="fa fa-spinner fa-spin" v-if="searchLdr"></i> </button>
                      <button type="button" class="btn btn-primary" v-on:click="getAllPosts()">Clear Filter <i class="fa fa-spinner fa-spin" v-if="clearsearch"></i> </button>
                   </div>
               </div>
               <div class="row">
                  <table class="table table-bordered">
                     <thead>
                        <tr>
                           <th>#</th>
                           <th>Update</th>
                           <th>Username</th>
                           <th>Category</th>
                           <th>Date</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody>
                        <tr v-if="loading">
                           <td colspan="3"><i class="fa fa-spinner fa-spin"></i></td>
                        </tr>
                        <tr v-for="(cat, id) in posts">
                           <td>{{id+1}}</td>
                           <td>{{cat.text}}</td>
                           <td>{{cat.username}}</td>
                           <td>{{cat.category_name}}</td>
                           <td>{{formatDate(cat.time)}}</td>
                           <td>
                              <a href="Javascript:;" data-toggle="modal" data-target="#editModal" v-on:click="editUserPost(cat)">Edit</a> | 
                              <a href="Javascript:;" v-on:click="deleteUserPost(cat)">Delete</a>
                           </td>
                        </tr>
                     </tbody>
                  </table>
               </div>
            </div>
         </div>
      </div>
      
       <!-- Edit Modal -->
      <div class="modal" id="editModal">
          <div class="modal-dialog">
            <div class="modal-content">
        
              <!-- Modal Header -->
              <div class="modal-header">
                <h4 class="modal-title">Edit Post</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>
        
              <!-- Modal body -->
              <div class="modal-body">
                  <form enctype="multipart/form-data" method="post" action="https://p-tweets.com/talk/native_api/cpanel/update_post">
                    <input type="text" name="id" style="display:none" class="id">
                  <div class="form-group">
                    <label for="text">Text:</label>
                    <textarea name="text" v-model='editObj.text' class="form-control" placeholder="Enter text" cols="10" style="background: transparent"></textarea>
                  </div>
                  
                  <div class="form-group mt-4">
                    <label for="text">Category:</label>
                    <select class="form-control" v-model='editObj.category_id' name="category_id">
                        <option v-for="(cat, id) in categories" :value=cat.id>{{cat.name}}</option>  
                    </select>
                  </div>
                  
                  <div class="form-group mt-4">
                    <label for="text">Photo:</label>
                    <img :src="'https://p-tweets.com/talk/'+editObj.src" style="width: 250px;"> 
                  </div>
                  
                  <div class="form-group mt-4">
                    <label for="text">Image:</label>
                    <input type="file" v-model='editObj.image' name="image">
                  </div>
                  
                  <button type="submit" class="btn btn-primary mt-4" >Update</button>
                  </form>
              </div>
        
              <!-- Modal footer -->
              <!--<div class="modal-footer">-->
              <!--  <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>-->
              <!--</div>-->
        
            </div>
          </div>
        </div>
   </div>
</div>
<?php echo cl_template('cpanel/assets/posts_pages/scripts/app_master_script'); ?>
