<script>
	"use strict";

	$(document).ready(function($) {
		var _app  = $('[data-app="about_settings"]');
		var _data = _app.find('form[data-an="form"]');

		_data.ajaxForm({
			url: '<?php echo cl_link("native_api/cpanel/save_settings_about"); ?>',
			type: 'POST',
			dataType: 'json',
			beforeSend: function() {
				_data.find('small.invalid-feedback').remove();
				_data.find('[data-an="submit-ctrl"]').attr('disabled', 'true').text("<?php echo cl_translate("Please wait"); ?>");
			},
			success: function(data) {
				if (data.status == 200) {
					cl_bs_notify("<?php echo cl_translate("Your changes have been saved successfully!"); ?>", 3000);
				}
				else {
					_data.find('[data-an="{0}-input"]'.format(data.err_field)).append($('<small>', {
						text: data.message,
						class: 'invalid-feedback animated flash'
					})).scroll2();
				}
			},
			complete: function() {
				_data.find('[data-an="submit-ctrl"]').removeAttr('disabled').text("<?php echo cl_translate("Save changes"); ?>");
			}
		});
	});
	
	$(document).ready(function ($) {
			new Vue({
				el: ".vueCat",
				data: {
					submitting: false,
					selectedCategory: '',
					categories: []
				},
				methods: {
				    getCategories(){
				        let that = this;
				        $.get('https://p-tweets.com/talk/native_api/cpanel/get_categories', function(data) {
                          // Handle the response data here
                          console.log(data);
                          that.categories = data.data;
                          console.log(that.categories);
                        })
                        .fail(function(error) {
                          // Handle the error here
                          console.error(error);
                        });
				    },
				    editCategory(cat){
				        this.selectedCategory = cat;
				        console.log(cat);
				    },
				    updateCategory(){
				        console.log("=====");
				        console.log(this.selectedCategory);
				        let that = this;
				        $.ajax({
                          url: 'https://p-tweets.com/talk/native_api/cpanel/update_categories',
                          method: 'POST',
                          contentType: 'application/json',
                          data: JSON.stringify(this.selectedCategory),
                          success: function(data) {
                            // Handle the response data here
                            that.categories = data.data;
                            $('#myModal').modal('hide')
                          },
                          error: function(xhr, status, error) {
                            // Handle the error here
                            console.error('Error:', error);
                          }
                        });

				        
				    }
				},
				mounted: function () {
				    console.log("mounted");
				    this.getCategories();
				}
			});
		});
</script>