<div class="cp-app-container" data-app="about_settings">
<div class="container-fluid">        
            <div class="page-title">
              <div class="row">
                <div class="col-6">
                  <h3> Categories Page </h3>
                </div>
                <div class="col-6">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item"> <a href="<?php echo cl_link('admin_panel'); ?>">                                    <i data-feather="home"></i></a></li>
                    <li class="breadcrumb-item">    <?php echo cl_translate('Categories'); ?></li>
                  </ol>
                </div>
              </div>
            </div>
          </div>

 
     <div class="container-fluid">
            <div class="row">
              <div class="col-sm-12">
                <div class="card"  style="padding: 15px;">
                  <div class="card-header">
                    <h5>
                       Manage Categories
                    </h5>
                </div>

                <div class="vueCat">
                    <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr v-for="(cat, id) in categories">
                        <td>{{id+1}}</td>
                        <td>{{cat.name}}</td>
                        <td>
                            <a href="Javascript:;"  data-toggle="modal" data-target="#myModal" v-on:click="editCategory(cat)">Edit</a> | 
                            <a href="Javascript:;">Delete</a>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                  
                  
                  
                    <!-- The Modal -->
                    <div class="modal" id="myModal">
                      <div class="modal-dialog">
                        <div class="modal-content">
                    
                          <!-- Modal Header -->
                          <div class="modal-header">
                            <h4 class="modal-title">Edit Category</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                          </div>
                    
                          <!-- Modal body -->
                          <div class="modal-body">
                              <div class="form-group">
                                <label for="name">Name:</label>
                                <input type="text" class="form-control" placeholder="Enter name" id="name" v-model='selectedCategory.name' >
                              </div>
                          
                              <button type="button" v-on:click="updateCategory()" class="btn btn-primary">Update</button>
                          </div>
                    
                          <!-- Modal footer -->
                          <!--<div class="modal-footer">-->
                          <!--  <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>-->
                          <!--</div>-->
                    
                        </div>
                      </div>
                    </div>
                  
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<?php echo cl_template('cpanel/assets/categories_pages/scripts/app_master_script'); ?>
