<script>
	
	"use strict";

	$(document).ready(function($) {
        
        $.get('https://p-tweets.com/talk/native_api/home/banned_words', function(data) {
          // Handle the response data here
          console.log(data);
              let jsonData = data.data;
              console.log("jsonData");
              console.log(jsonData);
              window.banned_words = jsonData
        })
        .fail(function(error) {
          // Handle the error here
          console.error(error);
        });
        
        // $.get('https://p-tweets.com/talk/native_api/cpanel/get_all_categories', function(data) {
        $.get('https://p-tweets.com/talk/native_api/home/get_all_categories', function(data) {
          // Handle the response data here
          console.log(data);
              let jsonData = data.data;
              const $categorySelect = $('.categorySelect');

              // Add options to select box
                jsonData.forEach(category => {
                    const indentation = category.parent_id !== null ? '&nbsp;&nbsp;&nbsp;' : '';
                    $categorySelect.append(`<option value="${category.id}">${indentation}${category.name}</option>`);
                });
        })
        .fail(function(error) {
          // Handle the error here
          console.error(error);
        });

		<?php echo cl_js_template('apps/timeline/scripts/js/pubbox_mixin'); ?>
		
		if ($("form#vue-pubbox-app-2").length) {
			var pubbox_app_2 = new Vue({
				el:"#vue-pubbox-app-2",
				mixins: [pubbox_form_app_mixin]
			});

			SMColibri.extend_vue('pubbox2', pubbox_app_2);

			$(document).on('hidden.bs.modal', 'div#add_new_post', function () {  
			    console.log('hide now');
		        pubbox_app_2.thread_id    = 0;
		        pubbox_app_2.post_privacy = "everyone";
		    });
		    
            $(document).on('shown.bs.modal', 'div#add_new_post', function () {
              console.log("modal show");
              console.log($(this));
              setTimeout(() => {
                  console.log("afer 3 secs"); 
                  $('.modal [data-toggle="tooltip"]').tooltip({trigger: 'hover'}); 
              })
             
            });
		}
		if ($("form#vue-pubbox-app-3").length) {
			var pubbox_app_2 = new Vue({
				el:"#vue-pubbox-app-3",
				mixins: [pubbox_form_app_mixin]
			});

			SMColibri.extend_vue('pubbox2', pubbox_app_2);

			$(document).on('hidden.bs.modal', 'div#add_new_post', function () {  
		        pubbox_app_2.thread_id    = 0;
		        pubbox_app_2.post_privacy = "everyone";
		    });
		}
		
	});
	
	
document.addEventListener('DOMContentLoaded', function () {
    try{
        var catId = <?php echo ($_GET['cat_id'] ?? '0'); ?>;
    } catch(e){
        console.log(e);
    }
  
  console.log("catId")
  console.log(catId)
if(catId != 0){return}
    
  // Get all post list items
  const postListItems = document.querySelectorAll('.post-list-item');
  console.log(postListItems);

  // Hide the first three elements and apply initial transform
  postListItems[0].style.display = 'none';
  postListItems[1].style.display = 'none';
  postListItems[2].style.display = 'none';
  postListItems[0].style.transform = 'translateY(-100%)';
  postListItems[1].style.transform = 'translateY(-100%)';
  postListItems[2].style.transform = 'translateY(-100%)';

  setTimeout(() => {
    [2, 1, 0].forEach((val, i) => {
      setTimeout(() => {
        postListItems[val].style.display = 'block'; // Show the element
        postListItems[val].style.transition = 'transform 0.5s';
        postListItems[val].style.transform = 'translateY(0)';
      }, 4000 * i);
    });
  }, 3000);
});
	
</script>
